INSERT INTO USERS(ID,EMAIL,PASSWORD_HASH,ROLE,NAME,CREATED_AT)
VALUES (RANDOM_UUID(),'admin@stayease.com','$2a$10$U1E/jEt3fvDiv3SNeyPLVuthzVU.G8qQoL3dXabaE0CZkNd0GMpZe','ADMIN','Admin',CURRENT_TIMESTAMP()),
(RANDOM_UUID(),'mgr1@stayease.com','$2a$10$U1E/jEt3fvDiv3SNeyPLVuthzVU.G8qQoL3dXabaE0CZkNd0GMpZe','MANAGER','Hotel Manager',CURRENT_TIMESTAMP()),
(RANDOM_UUID(),'guest1@stayease.com','$2a$10$U1E/jEt3fvDiv3SNeyPLVuthzVU.G8qQoL3dXabaE0CZkNd0GMpZe','GUEST','Rohit Verma',CURRENT_TIMESTAMP());


INSERT INTO HOTEL(ID,NAME,CITY,STAR_RATING,DESCRIPTION,COVER_IMAGE_URL,MANAGER_ID,CREATED_AT)
VALUES
(RANDOM_UUID(),'Sunset Palms','Goa',4,'Beachfront resort with pool',
'https://picsum.photos/seed/hotel1/400',
(SELECT ID FROM USERS WHERE EMAIL='mgr1@stayease.com'),CURRENT_TIMESTAMP()),
(RANDOM_UUID(),'City Inn','Goa',3,'Budget-friendly city centre hotel',
'https://picsum.photos/seed/hotel2/400',
(SELECT ID FROM USERS WHERE EMAIL='mgr1@stayease.com'),CURRENT_TIMESTAMP());


INSERT INTO ROOM(ID,HOTEL_ID,ROOM_NUMBER,ROOM_TYPE,PRICE_PER_NIGHT,MAX_OCCUPANCY,ACTIVE,CREATED_AT)
VALUES
(RANDOM_UUID(),(SELECT ID FROM HOTEL WHERE NAME='Sunset Palms'),'101','Double',3500.00,2,true,CURRENT_TIMESTAMP()),
(RANDOM_UUID(),(SELECT ID FROM HOTEL WHERE NAME='Sunset Palms'),'201','Suite',7000.00,3,true,CURRENT_TIMESTAMP()),
(RANDOM_UUID(),(SELECT ID FROM HOTEL WHERE NAME='City Inn'),'101','Single',1500.00,1,true,CURRENT_TIMESTAMP());