export const strings = {
  app: {
    brand: 'StayEase',
  },
  nav: {
    home: 'Home',
    myStays: 'My Stays',
    manager: 'Manager',
    admin: 'Admin',
    loginRegister: 'Login / Register',
    logout: 'Logout',
  },
  auth: {
    login: 'Login',
    register: 'Register',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    createAccount: 'Create an account',
    haveAccount: 'Have an account?',
    loggedIn: 'Logged in',
    accountCreated: 'Account created',
    authFailed: 'Auth failed',
    nameRequired: 'Name is required',
    emailRequired: 'Email is required',
    emailInvalid: 'Enter a valid email address',
    passwordRequired: 'Password is required',
    passwordTooShort: 'Password must be at least 6 characters',
    loggedOut: 'Logged out',
  },
  home: {
    title: 'Find and book hotel rooms — simple, in minutes',
    subtitle: 'Search hotels by city and dates. This is a UI-only mock implementing the StayEase flows.',
    seededHotels: 'Seeded hotels',
    cityHint: 'Try searching for city: ',
    cityExample: 'Goa',
    pickDates: 'and pick dates.',
  },
  search: {
    destination: 'Destination',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    searchHotels: 'Search Hotels',
    cityRequired: 'City is required',
    datesRequired: 'Check-in and Check-out are required',
    checkOutAfterCheckIn: 'Check-out must be after check-in',
    placeholderCity: 'e.g. Goa',
  },
  hotels: {
    title: 'Hotels',
    loading: 'Loading…',
    noHotels: 'No hotels found for that city.',
  },
  hotelDetail: {
    loading: 'Loading…',
    hotelNotFound: 'Hotel not found',
    availableRooms: 'Available Rooms',
    noRooms: 'No rooms available for selected dates.',
    pleaseLoginToBook: 'Please login to continue booking',
  },
  hotelCard: {
    rateFrom: 'Rate from',
    perNight: 'per night',
    viewRooms: 'View Rooms',
  },
  roomCard: {
    roomType: 'Room type',
    roomNumberPrefix: 'No. ',
    sleepsUpTo: 'Sleeps up to ',
    rate: 'Rate',
    perNight: 'per night',
    book: 'Book',
  },
  booking: {
    title: 'Confirm Booking',
    hotel: 'Hotel:',
    checkIn: 'Check-in:',
    checkOut: 'Check-out:',
    bookingConfirmed: 'Booking Confirmed',
    bookingId: 'Booking ID:',
    viewMyStays: 'View My Stays',
    pleaseLogin: 'Please login to confirm booking',
    confirmBooking: 'Confirm Booking',
    bookingLoading: 'Booking…',
    bookingFailed: 'Booking failed',
    bookingSuccess: 'Booking confirmed',
    loadingHotel: 'Loading hotel…',
  },
  manager: {
    title: 'Manager Dashboard',
    accessDenied: 'Access denied: manager only',
    hotels: 'My Hotels',
    selectHotel: 'Select hotel',
    noHotels: 'No hotels are assigned to you.',
    createRoom: 'Create Room',
    roomNumber: 'Room number',
    roomType: 'Room type',
    pricePerNight: 'Price per night',
    maxOccupancy: 'Maximum occupancy',
    createRoomAction: 'Create room',
    roomCreated: 'Room created',
    roomCreateFailed: 'Room creation failed',
    hotelRequired: 'Select a hotel',
    roomNumberRequired: 'Room number must be greater than 0',
    priceRequired: 'Price must be greater than 0',
    occupancyRequired: 'Maximum occupancy must be greater than 0',
    myRooms: 'My Rooms',
    number: 'Number',
    type: 'Type',
    price: 'Price',
    active: 'Active',
    yes: 'Yes',
    no: 'No',
    upcomingBookings: 'Upcoming Bookings',
    booking: 'Booking',
    room: 'Room',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
  },
  myStays: {
    title: 'My Stays',
    loading: 'Loading…',
    pleaseLogin: 'Please login to view your stays',
    hotel: 'Hotel',
    room: 'Room',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    total: 'Total',
    status: 'Status',
    cancel: 'Cancel',
    cancelFailed: 'Cancel failed',
  },
  admin: {
    title: 'Admin Dashboard',
    accessDenied: 'Access denied: admin only',
    createHotel: 'Create New Hotel',
    editHotel: 'Edit Hotel: ',
    saveChanges: 'Save changes',
    createHotelAction: 'Create hotel',
    cancel: 'Cancel',
    hotelName: 'Hotel name',
    city: 'City',
    starRating: 'Star rating',
    manager: 'Manager',
    coverImageUrl: 'Cover image URL',
    description: 'Description',
    hotels: 'Hotels',
    users: 'Users',
    allBookings: 'All Bookings',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    ref: 'Ref',
    user: 'User',
    hotel: 'Hotel',
    room: 'Room',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    status: 'Status',
    deleteHotelConfirm: 'Delete hotel "{name}"? This will remove its rooms.',
    hotelDeleted: 'Hotel deleted',
    deleteFailed: 'Delete failed',
    nameAndCityRequired: 'Name and city required',
    hotelUpdated: 'Hotel updated',
    hotelCreated: 'Hotel created',
    saveFailed: 'Save failed',
    noManager: '(none)',
    none: '-',
    edit: 'Edit',
    delete: 'Delete',
  },
  common: {
    yes: 'Yes',
    no: 'No',
    loading: 'Loading…',
    error: 'Error',
    success: 'Success',
    info: 'Info',
    warning: 'Warning',
  },
} as const;
